#!/bin/bash
jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @jupyterlab/hub-extension@0.12 \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension
conda uninstall -y --force dask-core
pip install git+https://github.com/eriknw/dask.git@fix_order_gh5859
#EOF
